Repository IBM/ibm-spectrum-scale-csi-operator, pull requests merged in 2019-12, with the labels that each got.

#85 CSV Fix for OLM Deployment
  stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator/deploy/crds/ibm-spectrum-scale-csi-operator-cr.yaml
  stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator/deploy/crds/ibm-spectrum-scale-csi-operator-crd.yaml
  stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator/deploy/olm-catalog/ibm-spectrum-scale-csi-operator/1.0.0/ibm-spectrum-scale-csi-operator-crd.yaml
  stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator/deploy/olm-catalog/ibm-spectrum-scale-csi-operator/1.0.0/ibm-spectrum-scale-csi-operator.v1.0.0.clusterserviceversion.yaml
  stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator/deploy/olm-catalog/ibm-spectrum-scale-csi-operator/ibm-spectrum-scale-csi-operator.package.yaml
  stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator/deploy/olm-scripts/operator-source-oc.yaml
  stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator/deploy/olm-scripts/operator-source.yaml
  stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator/deploy/operator.yaml
  stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator/deploy/role.yaml
  stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator/deploy/role_binding.yaml
  stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator/deploy/service_account.yaml
  stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator/hacks/relabel.py
Labels: Component: Bundling, Environment: Kubernetes, Environment: OpenShift, Phase: Test, Severity: 1 (blocking), Type: Enhancement

#75 Automatically generate a single yaml file that users can download to simplify the operator deployment
  .gitignore
  .travis.yml
  ansible/generate-playbook.yaml
  ansible/generate/create_files.yaml
  docs/source/conf.py
  docs/source/deployment/index.rst
  docs/source/deployment/manual.rst
  docs/source/deployment/olm.rst
  docs/source/developers/clone.rst
  docs/source/developers/deployment.rst
  docs/source/developers/index.rst
  docs/source/get-started/index.rst
  docs/source/get-started/quickstart.md
  docs/source/index.rst
  docs/source/olm.md
  docs/source/troubleshoot/index.rst
  docs/source/troubleshoot/operator-sdk/2094.rst
  docs/source/troubleshoot/operator-sdk/index.rst
  generated/installer/ibm-spectrum-scale-csi-operator.yaml
  stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator/deploy/crds/ibm-spectrum-scale-csi-operator-cr.yaml
Labels: Component: Automation, Component: Documentation, Phase: Development, Severity: 3, Type: Documentation, Type: Enhancement

#88 Cluster Service Version Refinements and Automation
  .travis.yml
  ansible/cert-playbook.yaml
  ansible/cert/inventory
  ansible/cert/verify_operator.yaml
  docs/source/get-started/quickstart.md
  stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator/deploy/crds/ibm-spectrum-scale-csi-operator-cr.yaml
  stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator/deploy/olm-catalog/ibm-spectrum-scale-csi-operator/1.0.0/ibm-spectrum-scale-csi-operator.v1.0.0.clusterserviceversion.yaml
  stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator/deploy/olm-catalog/ibm-spectrum-scale-csi-operator/ibm-spectrum-scale-csi-operator.package.yaml
  stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator/hacks/csi-scale-deploy.py
  stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator/hacks/csv_copy_cr.py
  stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator/hacks/csv_copy_crd_descriptions.py
  stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator/hacks/csv_copy_docs.py
  stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator/hacks/csv_prep.py
  stable/ibm-spectrum-scale-csi-operator-bundle/operators/ibm-spectrum-scale-csi-operator/hacks/default_crd_copy.sh
Labels: Component: Automation, Component: Bundling, Component: Certification, Component: Documentation, Environment: Kubernetes, Environment: OpenShift, Phase: Development, Severity: 2 (must fix), Type: Documentation, Type: Enhancement

#95 Proposing this script to have a consistent way to generate release tar files to upload to GitHub
  .gitignore
  docs/source/deployment/manual.rst
  tools/create_release_tar.sh
Labels: Component: Automation, Component: Bundling, Environment: Kubernetes, Environment: OpenShift, Phase: Development, Severity: 3, Type: Enhancement
